# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AccountStatus do
  @moduledoc """
  Outcome of one connected account's contribution to a fan-out call. Every connection that participated appears in `Envelope.accounts` exactly once, regardless of whether it succeeded, errored, or returned zero items. 
  """

  @derive JSON.Encoder
  defstruct [
    :provider,
    :accountId,
    :accountName,
    :status,
    :error,
    :nextPageToken
  ]

  @type t :: %__MODULE__{
    :provider => String.t,
    :accountId => String.t,
    :accountName => String.t | nil,
    :status => String.t,
    :error => Spatio.Model.AccountError.t | nil,
    :nextPageToken => String.t | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:error, :struct, Spatio.Model.AccountError)
  end
end

