# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AccountError do
  @moduledoc """
  Per-account failure attached to `AccountStatus.error` inside a fan-out `Envelope`. `code` is machine-readable and stable across releases for the canonical values (`auth_expired`, `rate_limited`, `provider_5xx`, `timeout`); `unknown` is a fallback and should not be relied on. 
  """

  @derive JSON.Encoder
  defstruct [
    :code,
    :message
  ]

  @type t :: %__MODULE__{
    :code => String.t,
    :message => String.t
  }

  def decode(value) do
    value
  end
end

