# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AccountPlan do
  @moduledoc """
  Subscription summary. `tier` is the canonical billing tier (uppercased: `FREE`, `PRO`, `MAX`, `ENTERPRISE`); `display_name` is the lowercase user-facing label. 
  """

  @derive JSON.Encoder
  defstruct [
    :tier,
    :display_name,
    :subscription_status,
    :trial_ends_at
  ]

  @type t :: %__MODULE__{
    :tier => String.t,
    :display_name => String.t,
    :subscription_status => String.t,
    :trial_ends_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

