# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AccountTierDetails do
  @moduledoc """
  Per-tier capability + quota envelope. Numeric quotas use 0/-1 idioms; treat large negatives as \"unlimited.\"
  """

  @derive JSON.Encoder
  defstruct [
    :tier,
    :daily_api_calls,
    :max_connected_accounts,
    :max_email_sends_per_day,
    :max_notes,
    :max_sheets,
    :max_slides,
    :max_files,
    :max_tasks,
    :max_team_members,
    :max_workspaces,
    :storage_gb,
    :has_automations,
    :has_advanced_automations,
    :has_full_api_access
  ]

  @type t :: %__MODULE__{
    :tier => String.t,
    :daily_api_calls => integer() | nil,
    :max_connected_accounts => integer() | nil,
    :max_email_sends_per_day => integer() | nil,
    :max_notes => integer() | nil,
    :max_sheets => integer() | nil,
    :max_slides => integer() | nil,
    :max_files => integer() | nil,
    :max_tasks => integer() | nil,
    :max_team_members => integer() | nil,
    :max_workspaces => integer() | nil,
    :storage_gb => integer() | nil,
    :has_automations => boolean() | nil,
    :has_advanced_automations => boolean() | nil,
    :has_full_api_access => boolean() | nil
  }

  def decode(value) do
    value
  end
end

