# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AccountChoice do
  @moduledoc """
  One of the candidates returned alongside an `ambiguous_account` error so the client can prompt the user to pick a target account. 
  """

  @derive JSON.Encoder
  defstruct [
    :provider,
    :accountId,
    :accountName
  ]

  @type t :: %__MODULE__{
    :provider => String.t,
    :accountId => String.t,
    :accountName => String.t | nil
  }

  def decode(value) do
    value
  end
end

