# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ActionDescriptor do
  @moduledoc """
  Action manifest entry surfaced by the agent platform. The `inputType`/`outputType` references point at internal Go types; treat them as opaque labels. 
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :canonical_id,
    :name,
    :description,
    :category,
    :inputType,
    :outputType,
    :metadata
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :canonical_id => String.t | nil,
    :name => String.t | nil,
    :description => String.t | nil,
    :category => String.t | nil,
    :inputType => String.t | nil,
    :outputType => String.t | nil,
    :metadata => %{optional(String.t) => any()} | nil
  }

  def decode(value) do
    value
  end
end

