# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AddWorkspaceMemberRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :role
  ]

  @type t :: %__MODULE__{
    :email => String.t,
    :role => String.t
  }

  def decode(value) do
    value
  end
end

