# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AgentConversation do
  @moduledoc """
  LLM conversation tracked by the agent platform (distinct from /v1/conversations which is the renderer-driven sidebar persistence). 
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :agentId,
    :title,
    :metadata,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :agentId => String.t | nil,
    :title => String.t | nil,
    :metadata => %{optional(String.t) => any()} | nil,
    :createdAt => DateTime.t | nil,
    :updatedAt => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

