# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AgentListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :agents,
    :hasMore,
    :total,
    :totalCount
  ]

  @type t :: %__MODULE__{
    :agents => [Spatio.Model.Agent.t] | nil,
    :hasMore => boolean() | nil,
    :total => integer() | nil,
    :totalCount => integer() | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:agents, :list, Spatio.Model.Agent)
  end
end

