# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AgentTaskUsage do
  @moduledoc """
  Free-trial agent-task gate. `allowed` is the only field clients must check before issuing a turn. Paid users get `paid: true, allowed: true` with the count fields null. 
  """

  @derive JSON.Encoder
  defstruct [
    :allowed,
    :task_count,
    :daily_limit,
    :trial_ends_at,
    :paid
  ]

  @type t :: %__MODULE__{
    :allowed => boolean(),
    :task_count => integer() | nil,
    :daily_limit => integer() | nil,
    :trial_ends_at => DateTime.t | nil,
    :paid => boolean() | nil
  }

  def decode(value) do
    value
  end
end

