# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AgentMessageListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :messages,
    :total
  ]

  @type t :: %__MODULE__{
    :messages => [Spatio.Model.AgentMessage.t],
    :total => integer() | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:messages, :list, Spatio.Model.AgentMessage)
  end
end

