# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AgentSessionContext do
  @moduledoc """
  Identity bundle returned to the agent at SessionStart. One round-trip provides user + current org/workspace + connected accounts so the agent doesn't fish on its first turn. 
  """

  @derive JSON.Encoder
  defstruct [
    :user,
    :currentOrganization,
    :currentWorkspace,
    :connectedAccounts
  ]

  @type t :: %__MODULE__{
    :user => %{optional(String.t) => any()} | nil,
    :currentOrganization => %{optional(String.t) => any()} | nil,
    :currentWorkspace => %{optional(String.t) => any()} | nil,
    :connectedAccounts => [%{optional(String.t) => any()}] | nil
  }

  def decode(value) do
    value
  end
end

