# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.Agent do
  @moduledoc """
  Stored agent configuration (system prompt + tool selection). User-defined agents and preconfigured agents share this shape. 
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :systemPrompt,
    :tools,
    :icon,
    :color,
    :isDefault,
    :isPreconfigured,
    :createdAt,
    :updatedAt,
    :metadata
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t | nil,
    :description => String.t | nil,
    :systemPrompt => String.t | nil,
    :tools => [String.t] | nil,
    :icon => String.t | nil,
    :color => String.t | nil,
    :isDefault => boolean() | nil,
    :isPreconfigured => boolean() | nil,
    :createdAt => DateTime.t | nil,
    :updatedAt => DateTime.t | nil,
    :metadata => %{optional(String.t) => any()} | nil
  }

  def decode(value) do
    value
  end
end

