# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.App do
  @moduledoc """
  Locally-built prototype app rendered in an Electron <webview>. `projectPath` is the on-disk root; file ops are scoped to it. 
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :projectPath,
    :icon,
    :color,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t | nil,
    :description => String.t | nil,
    :projectPath => String.t | nil,
    :icon => String.t | nil,
    :color => String.t | nil,
    :createdAt => DateTime.t | nil,
    :updatedAt => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

