# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.AssignContactCategoryRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :category_id
  ]

  @type t :: %__MODULE__{
    :category_id => String.t
  }

  def decode(value) do
    value
  end
end

