# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.Attachment do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :title,
    :mime_type,
    :url,
    :size
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :title => String.t,
    :mime_type => String.t | nil,
    :url => Uri,
    :size => integer() | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:url, :struct, Spatio.Model.Uri)
  end
end

