# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.BulkDeleteEmailsResponse do
  @moduledoc """
  Partial-success envelope for `bulkDeleteEmails`.
  """

  @derive JSON.Encoder
  defstruct [
    :success,
    :deleted,
    :failed
  ]

  @type t :: %__MODULE__{
    :success => boolean(),
    :deleted => [String.t],
    :failed => [Spatio.Model.BulkArchiveResponseFailedInner.t]
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:failed, :list, Spatio.Model.BulkArchiveResponseFailedInner)
  end
end

