# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.BulkUpdateTasksResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :success,
    :affectedCount,
    :tasks,
    :failed
  ]

  @type t :: %__MODULE__{
    :success => boolean(),
    :affectedCount => integer(),
    :tasks => [Spatio.Model.Task.t],
    :failed => [Spatio.Model.BulkDeleteTasksResponseFailedInner.t]
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:tasks, :list, Spatio.Model.Task)
     |> Deserializer.deserialize(:failed, :list, Spatio.Model.BulkDeleteTasksResponseFailedInner)
  end
end

