# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.BulkUpdateTasksRequest do
  @moduledoc """
  Apply the same `updates` payload to every id. Same parallel AccountIDs convention as bulk delete. 
  """

  @derive JSON.Encoder
  defstruct [
    :taskIds,
    :accountIds,
    :accountId,
    :updates
  ]

  @type t :: %__MODULE__{
    :taskIds => [String.t],
    :accountIds => [String.t] | nil,
    :accountId => String.t | nil,
    :updates => Spatio.Model.UpdateTaskRequest.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:updates, :struct, Spatio.Model.UpdateTaskRequest)
  end
end

