# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.BulkArchiveResponseFailedInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :messageId,
    :error
  ]

  @type t :: %__MODULE__{
    :messageId => String.t,
    :error => String.t
  }

  def decode(value) do
    value
  end
end

