# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.BulkFilesResponseFailedInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :fileId,
    :error
  ]

  @type t :: %__MODULE__{
    :fileId => String.t,
    :error => String.t
  }

  def decode(value) do
    value
  end
end

