# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.BulkMarkReadResponse do
  @moduledoc """
  Partial-success envelope for `bulkMarkEmailsRead`. `updated` is a count (not an array — distinct from archive/delete which return the actual id list). The failed-row shape uses `id` (also distinct — renderer-compat legacy). 
  """

  @derive JSON.Encoder
  defstruct [
    :updated,
    :failed
  ]

  @type t :: %__MODULE__{
    :updated => integer(),
    :failed => [Spatio.Model.BulkMarkReadResponseFailedInner.t]
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:failed, :list, Spatio.Model.BulkMarkReadResponseFailedInner)
  end
end

