# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.BulkDeleteTasksResponse do
  @moduledoc """
  Partial-success envelope. `success` is `true` only when zero failures; `affectedCount` is the deleted count; `taskIds` lists the ids that succeeded; `failed` lists per-id errors. 
  """

  @derive JSON.Encoder
  defstruct [
    :success,
    :affectedCount,
    :taskIds,
    :failed
  ]

  @type t :: %__MODULE__{
    :success => boolean(),
    :affectedCount => integer(),
    :taskIds => [String.t],
    :failed => [Spatio.Model.BulkDeleteTasksResponseFailedInner.t]
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:failed, :list, Spatio.Model.BulkDeleteTasksResponseFailedInner)
  end
end

