# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.BulkMoveFilesRequest do
  @moduledoc """
  Move multiple files to one target folder. `targetFolderId` is the canonical name; `folderId` is accepted as a renderer-compat alias. 
  """

  @derive JSON.Encoder
  defstruct [
    :fileIds,
    :accountIds,
    :accountId,
    :targetFolderId,
    :folderId
  ]

  @type t :: %__MODULE__{
    :fileIds => [String.t] | nil,
    :accountIds => [String.t] | nil,
    :accountId => String.t | nil,
    :targetFolderId => String.t | nil,
    :folderId => String.t | nil
  }

  def decode(value) do
    value
  end
end

