# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.BulkDeleteEmailsRequest do
  @moduledoc """
  Soft-deletes by default (moves to provider trash). Set `permanent: true` to hard-delete. 
  """

  @derive JSON.Encoder
  defstruct [
    :accountId,
    :messageIds,
    :permanent
  ]

  @type t :: %__MODULE__{
    :accountId => String.t | nil,
    :messageIds => [String.t],
    :permanent => boolean() | nil
  }

  def decode(value) do
    value
  end
end

