# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.BulkMarkReadRequest do
  @moduledoc """
  Bulk shorthand for setting read state on many messages at once. `messageIds` accepts an array; the production handler also accepts a bare string for renderer-compat but the spec models the array shape only. `read` defaults to `true` when omitted. 
  """

  @derive JSON.Encoder
  defstruct [
    :accountId,
    :messageIds,
    :read
  ]

  @type t :: %__MODULE__{
    :accountId => String.t | nil,
    :messageIds => [String.t],
    :read => boolean() | nil
  }

  def decode(value) do
    value
  end
end

