# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CalendarAccountError do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :account_id,
    :account_name,
    :error_code,
    :error_message
  ]

  @type t :: %__MODULE__{
    :account_id => String.t,
    :account_name => String.t,
    :error_code => String.t,
    :error_message => String.t
  }

  def decode(value) do
    value
  end
end

