# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CalendarCapabilitiesResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :account_id,
    :provider_id,
    :capabilities
  ]

  @type t :: %__MODULE__{
    :account_id => String.t,
    :provider_id => String.t,
    :capabilities => %{optional(String.t) => any()}
  }

  def decode(value) do
    value
  end
end

