# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CalendarSyncResponse do
  @moduledoc """
  Returned by `POST /v1/calendar/sync`. Status code is `202` by default (sync jobs queued); `200` when called with `?wait=true` and all jobs finish within the 10-second polling budget. 
  """

  @derive JSON.Encoder
  defstruct [
    :enqueued,
    :jobs,
    :waited,
    :timed_out,
    :errors
  ]

  @type t :: %__MODULE__{
    :enqueued => integer(),
    :jobs => [String.t],
    :waited => boolean() | nil,
    :timed_out => boolean() | nil,
    :errors => [%{optional(String.t) => any()}] | nil
  }

  def decode(value) do
    value
  end
end

