# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CalendarProviderInfo do
  @moduledoc """
  Metadata about one registered calendar provider.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :display_name,
    :description,
    :is_system
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :display_name => String.t | nil,
    :description => String.t | nil,
    :is_system => boolean() | nil
  }

  def decode(value) do
    value
  end
end

