# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CallRecording do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :callId,
    :status,
    :startedAt,
    :endedAt,
    :url,
    :metadata
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :callId => String.t | nil,
    :status => String.t | nil,
    :startedAt => DateTime.t | nil,
    :endedAt => DateTime.t | nil,
    :url => String.t | nil,
    :metadata => %{optional(String.t) => any()} | nil
  }

  def decode(value) do
    value
  end
end

