# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CallListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :calls,
    :total
  ]

  @type t :: %__MODULE__{
    :calls => [Spatio.Model.SpatioCall.t] | nil,
    :total => integer() | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:calls, :list, Spatio.Model.SpatioCall)
  end
end

