# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CallRecordingListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :recordings
  ]

  @type t :: %__MODULE__{
    :recordings => [Spatio.Model.CallRecording.t] | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:recordings, :list, Spatio.Model.CallRecording)
  end
end

