# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ChangePasswordRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :currentPassword,
    :newPassword
  ]

  @type t :: %__MODULE__{
    :currentPassword => String.t | nil,
    :newPassword => String.t
  }

  def decode(value) do
    value
  end
end

