# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ChannelMembershipRequest do
  @moduledoc """
  Body for join/leave operations.
  """

  @derive JSON.Encoder
  defstruct [
    :accountId
  ]

  @type t :: %__MODULE__{
    :accountId => String.t | nil
  }

  def decode(value) do
    value
  end
end

