# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ClientRegistrationResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :client_id,
    :client_secret,
    :client_name,
    :redirect_uris,
    :grant_types,
    :response_types,
    :scope,
    :token_endpoint_auth_method,
    :registration_access_token,
    :registration_client_uri,
    :client_id_issued_at
  ]

  @type t :: %__MODULE__{
    :client_id => String.t,
    :client_secret => String.t | nil,
    :client_name => String.t,
    :redirect_uris => [String.t],
    :grant_types => [String.t] | nil,
    :response_types => [String.t] | nil,
    :scope => String.t | nil,
    :token_endpoint_auth_method => String.t | nil,
    :registration_access_token => String.t,
    :registration_client_uri => String.t | nil,
    :client_id_issued_at => integer()
  }

  def decode(value) do
    value
  end
end

