# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CommentMutationResponse do
  @moduledoc """
  Response for `POST` and `PATCH` on a comment.
  """

  @derive JSON.Encoder
  defstruct [
    :comment,
    :success
  ]

  @type t :: %__MODULE__{
    :comment => Spatio.Model.Comment.t,
    :success => boolean()
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:comment, :struct, Spatio.Model.Comment)
  end
end

