# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.Comment do
  @moduledoc """
  Threaded comment on a note. Top-level comments have `parentCommentId: null`; replies set it to the parent comment's id. `blockId` anchors the comment to a specific block; comments without a `blockId` are note-level (\"general\") comments. 
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :noteId,
    :parentCommentId,
    :blockId,
    :body,
    :createdAt,
    :updatedAt,
    :author
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :noteId => String.t,
    :parentCommentId => String.t | nil,
    :blockId => String.t | nil,
    :body => String.t,
    :createdAt => DateTime.t,
    :updatedAt => DateTime.t,
    :author => Spatio.Model.CommentAuthor.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:author, :struct, Spatio.Model.CommentAuthor)
  end
end

