# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CommentAuthor do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :email,
    :profilePhoto
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :email => String.t,
    :profilePhoto => Uri | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:profilePhoto, :struct, Spatio.Model.Uri)
  end
end

