# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CommitChunkedUploadResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :success,
    :fileId,
    :manifestId,
    :version,
    :totalSize,
    :physicalSize,
    :deduplicationPct,
    :totalBlocks,
    :newBlocks,
    :deduplicatedBlocks
  ]

  @type t :: %__MODULE__{
    :success => boolean(),
    :fileId => String.t,
    :manifestId => String.t,
    :version => integer(),
    :totalSize => integer(),
    :physicalSize => integer() | nil,
    :deduplicationPct => float() | nil,
    :totalBlocks => integer() | nil,
    :newBlocks => integer() | nil,
    :deduplicatedBlocks => integer() | nil
  }

  def decode(value) do
    value
  end
end

