# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ConferenceData do
  @moduledoc """
  Video/phone conference details. `type` is canonical (`spatio`, `meet`, `zoom`, `teams`); other provider-specific values are accepted as opaque strings. The Spatio invite email pipeline only fires for native events or events with `type: spatio`. 
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :uri,
    :meeting_id,
    :passcode,
    :access_code,
    :dial_in
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :uri => Uri,
    :meeting_id => String.t | nil,
    :passcode => String.t | nil,
    :access_code => String.t | nil,
    :dial_in => [String.t] | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:uri, :struct, Spatio.Model.Uri)
  end
end

