# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ConnectionListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :connections,
    :categories
  ]

  @type t :: %__MODULE__{
    :connections => [Spatio.Model.SpatioConnection.t],
    :categories => [String.t] | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:connections, :list, Spatio.Model.SpatioConnection)
  end
end

