# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ConnectionAccountListResponse do
  @moduledoc """
  `GET /v1/connections/user` returns `{connections, user_id}` (the per-provider connected-account list). Schema kept open pending a normalize-to-`accounts` migration. 
  """

  @derive JSON.Encoder
  defstruct [
    :connections,
    :user_id,
    :accounts
  ]

  @type t :: %__MODULE__{
    :connections => [map()] | nil,
    :user_id => String.t | nil,
    :accounts => [map()] | nil
  }

  def decode(value) do
    value
  end
end

