# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ContactProviderListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :providers
  ]

  @type t :: %__MODULE__{
    :providers => [Spatio.Model.ContactProvider.t]
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:providers, :list, Spatio.Model.ContactProvider)
  end
end

