# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ContactListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :contacts,
    :total_results,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :contacts => [Spatio.Model.Contact.t],
    :total_results => integer() | nil,
    :updated_at => DateTime.t | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:contacts, :list, Spatio.Model.Contact)
  end
end

