# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ContactCategory do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :color,
    :description,
    :organization_id
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :color => String.t | nil,
    :description => String.t | nil,
    :organization_id => String.t | nil
  }

  def decode(value) do
    value
  end
end

