# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ContactCategoryListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :categories
  ]

  @type t :: %__MODULE__{
    :categories => [Spatio.Model.ContactCategory.t] | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:categories, :list, Spatio.Model.ContactCategory)
  end
end

