# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ConversationMessage do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :conversation_id,
    :role,
    :content,
    :metadata,
    :created_at
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :conversation_id => String.t,
    :role => String.t,
    :content => String.t | nil,
    :metadata => %{optional(String.t) => any()} | nil,
    :created_at => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

