# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CoreAction do
  @moduledoc """
  Renderer-curated \"core action\" entry. These are the keyboard + command-palette surfaced actions; superset of the platform-tagged agent actions. Schema kept open since the platform metadata varies by category. 
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :platform,
    :category,
    :icon,
    :metadata
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t | nil,
    :description => String.t | nil,
    :platform => String.t | nil,
    :category => String.t | nil,
    :icon => String.t | nil,
    :metadata => %{optional(String.t) => any()} | nil
  }

  def decode(value) do
    value
  end
end

