# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreatePatRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :description,
    :scopes,
    :workspaceId,
    :expiresAt
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :description => String.t | nil,
    :scopes => [String.t] | nil,
    :workspaceId => String.t | nil,
    :expiresAt => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

