# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreateChannelRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :accountId,
    :name,
    :description,
    :isPrivate
  ]

  @type t :: %__MODULE__{
    :accountId => String.t | nil,
    :name => String.t,
    :description => String.t | nil,
    :isPrivate => boolean() | nil
  }

  def decode(value) do
    value
  end
end

