# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreateOrganizationInvitationRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :role,
    :workspaceId
  ]

  @type t :: %__MODULE__{
    :email => String.t,
    :role => String.t,
    :workspaceId => String.t | nil
  }

  def decode(value) do
    value
  end
end

