# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreateChannelResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :channel,
    :provider
  ]

  @type t :: %__MODULE__{
    :channel => Spatio.Model.Channel.t,
    :provider => String.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:channel, :struct, Spatio.Model.Channel)
  end
end

