# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreateFolderRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :accountId,
    :name,
    :parentId,
    :workspaceId,
    :organizationId
  ]

  @type t :: %__MODULE__{
    :accountId => String.t | nil,
    :name => String.t,
    :parentId => String.t | nil,
    :workspaceId => String.t | nil,
    :organizationId => String.t | nil
  }

  def decode(value) do
    value
  end
end

