# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreateAgentConversationRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :agentId,
    :title,
    :metadata
  ]

  @type t :: %__MODULE__{
    :agentId => String.t | nil,
    :title => String.t | nil,
    :metadata => %{optional(String.t) => any()} | nil
  }

  def decode(value) do
    value
  end
end

