# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreateCommentRequest do
  @moduledoc """
  Either `body` (preferred) or `content` (renderer parity with tasks) is required. Empty `parentCommentId`/`blockId` strings are treated as `null`. 
  """

  @derive JSON.Encoder
  defstruct [
    :body,
    :content,
    :parentCommentId,
    :blockId
  ]

  @type t :: %__MODULE__{
    :body => String.t | nil,
    :content => String.t | nil,
    :parentCommentId => String.t | nil,
    :blockId => String.t | nil
  }

  def decode(value) do
    value
  end
end

