# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreateSheetRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :description,
    :data,
    :rowCount,
    :columnCount,
    :accountId,
    :provider
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :description => String.t | nil,
    :data => %{optional(String.t) => any()} | nil,
    :rowCount => integer() | nil,
    :columnCount => integer() | nil,
    :accountId => String.t | nil,
    :provider => String.t | nil
  }

  def decode(value) do
    value
  end
end

