# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreateTaskRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :title,
    :description,
    :status,
    :dueDate,
    :priority,
    :labels,
    :tags,
    :assigneeId,
    :parentTaskId,
    :type,
    :sourcePlatform,
    :sourceId,
    :accountId,
    :provider
  ]

  @type t :: %__MODULE__{
    :title => String.t,
    :description => String.t | nil,
    :status => String.t | nil,
    :dueDate => DateTime.t | nil,
    :priority => String.t | nil,
    :labels => [String.t] | nil,
    :tags => [String.t] | nil,
    :assigneeId => String.t | nil,
    :parentTaskId => String.t | nil,
    :type => String.t | nil,
    :sourcePlatform => String.t | nil,
    :sourceId => String.t | nil,
    :accountId => String.t | nil,
    :provider => String.t | nil
  }

  def decode(value) do
    value
  end
end

