# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreateRoutineRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :workspaceId,
    :name,
    :description,
    :schedule,
    :metadata
  ]

  @type t :: %__MODULE__{
    :workspaceId => String.t | nil,
    :name => String.t,
    :description => String.t | nil,
    :schedule => %{optional(String.t) => any()} | nil,
    :metadata => %{optional(String.t) => any()} | nil
  }

  def decode(value) do
    value
  end
end

