# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreateBlockRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :type,
    :content,
    :parentId,
    :position,
    :properties
  ]

  @type t :: %__MODULE__{
    :type => Spatio.Model.BlockType.t,
    :content => Spatio.Model.BlockContent.t,
    :parentId => String.t | nil,
    :position => integer(),
    :properties => %{optional(String.t) => any()} | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:type, :struct, Spatio.Model.BlockType)
     |> Deserializer.deserialize(:content, :struct, Spatio.Model.BlockContent)
  end
end

