# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.CreateEventRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :account_id,
    :calendar_id,
    :event,
    :send_updates,
    :conference_type
  ]

  @type t :: %__MODULE__{
    :account_id => String.t,
    :calendar_id => String.t | nil,
    :event => Spatio.Model.SpatioEvent.t,
    :send_updates => String.t | nil,
    :conference_type => String.t | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:event, :struct, Spatio.Model.SpatioEvent)
  end
end

