# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.DiscoveryDocument do
  @moduledoc """
  OAuth 2.1 (RFC 8414) + OpenID Connect Discovery 1.0 metadata. Same payload returned from both well-known paths. 
  """

  @derive JSON.Encoder
  defstruct [
    :issuer,
    :authorization_endpoint,
    :token_endpoint,
    :registration_endpoint,
    :introspection_endpoint,
    :revocation_endpoint,
    :userinfo_endpoint,
    :jwks_uri,
    :response_types_supported,
    :grant_types_supported,
    :token_endpoint_auth_methods_supported,
    :code_challenge_methods_supported,
    :scopes_supported,
    :subject_types_supported,
    :id_token_signing_alg_values_supported,
    :prompt_values_supported,
    :claims_supported,
    :service_documentation
  ]

  @type t :: %__MODULE__{
    :issuer => String.t,
    :authorization_endpoint => String.t,
    :token_endpoint => String.t,
    :registration_endpoint => String.t | nil,
    :introspection_endpoint => String.t | nil,
    :revocation_endpoint => String.t | nil,
    :userinfo_endpoint => String.t | nil,
    :jwks_uri => String.t,
    :response_types_supported => [String.t] | nil,
    :grant_types_supported => [String.t] | nil,
    :token_endpoint_auth_methods_supported => [String.t] | nil,
    :code_challenge_methods_supported => [String.t] | nil,
    :scopes_supported => [String.t],
    :subject_types_supported => [String.t] | nil,
    :id_token_signing_alg_values_supported => [String.t] | nil,
    :prompt_values_supported => [String.t] | nil,
    :claims_supported => [String.t] | nil,
    :service_documentation => String.t | nil
  }

  def decode(value) do
    value
  end
end

