# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.DmAttachRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :kind,
    :url,
    :filename,
    :sizeBytes,
    :mimeType,
    :thumbnailUrl,
    :width,
    :height,
    :accountId
  ]

  @type t :: %__MODULE__{
    :kind => String.t,
    :url => Uri,
    :filename => String.t | nil,
    :sizeBytes => integer() | nil,
    :mimeType => String.t | nil,
    :thumbnailUrl => Uri | nil,
    :width => integer() | nil,
    :height => integer() | nil,
    :accountId => String.t | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:url, :struct, Spatio.Model.Uri)
     |> Deserializer.deserialize(:thumbnailUrl, :struct, Spatio.Model.Uri)
  end
end

