# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.DmMuteRequest do
  @moduledoc """
  Mute either until a specific time (`untilSeconds`, Unix epoch) or forever (`forever: true`). At least one must be set. 
  """

  @derive JSON.Encoder
  defstruct [
    :untilSeconds,
    :forever,
    :accountId
  ]

  @type t :: %__MODULE__{
    :untilSeconds => integer() | nil,
    :forever => boolean() | nil,
    :accountId => String.t | nil
  }

  def decode(value) do
    value
  end
end

