# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.DmThreadReplyRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :content,
    :accountId
  ]

  @type t :: %__MODULE__{
    :content => String.t,
    :accountId => String.t | nil
  }

  def decode(value) do
    value
  end
end

