# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.DownloadFileResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :signedUrl,
    :file
  ]

  @type t :: %__MODULE__{
    :signedUrl => Uri,
    :file => Spatio.Model.SpatioFile.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:signedUrl, :struct, Spatio.Model.Uri)
     |> Deserializer.deserialize(:file, :struct, Spatio.Model.SpatioFile)
  end
end

