# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.Draft do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :messageId,
    :threadId,
    :to,
    :cc,
    :bcc,
    :subject,
    :body,
    :html,
    :attachments,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :messageId => String.t,
    :threadId => String.t | nil,
    :to => [String.t] | nil,
    :cc => [String.t] | nil,
    :bcc => [String.t] | nil,
    :subject => String.t | nil,
    :body => String.t | nil,
    :html => boolean(),
    :attachments => [Spatio.Model.AttachmentMeta.t] | nil,
    :createdAt => DateTime.t,
    :updatedAt => DateTime.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:attachments, :list, Spatio.Model.AttachmentMeta)
  end
end

