# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.EnableShareRequest do
  @moduledoc """
  Body for `POST /v1/notes/{id}/share`. With `setPassword: false`, only the public flag is flipped — any existing password is preserved. With `setPassword: true`, the supplied `password` is applied (an empty string clears it). 
  """

  @derive JSON.Encoder
  defstruct [
    :setPassword,
    :password
  ]

  @type t :: %__MODULE__{
    :setPassword => boolean() | nil,
    :password => String.t | nil
  }

  def decode(value) do
    value
  end
end

