# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ExecuteActionResponse do
  @moduledoc """
  Generic action-execute result envelope. Tool-specific shape lives in `data`.
  """

  @derive JSON.Encoder
  defstruct [
    :ok,
    :data,
    :error
  ]

  @type t :: %__MODULE__{
    :ok => boolean() | nil,
    :data => %{optional(String.t) => any()} | nil,
    :error => String.t | nil
  }

  def decode(value) do
    value
  end
end

