# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ExecuteChatActionResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :success,
    :result
  ]

  @type t :: %__MODULE__{
    :success => boolean(),
    :result => any() | nil
  }

  def decode(value) do
    value
  end
end

