# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ExportPdfr2Response do
  @moduledoc """
  Response shape when the export was uploaded to R2 (`?storage=r2`). The streaming case (`?storage=stream`, default) returns a binary `application/pdf` body and is not modeled as a JSON schema. 
  """

  @derive JSON.Encoder
  defstruct [
    :storage,
    :url,
    :expiresAt,
    :size
  ]

  @type t :: %__MODULE__{
    :storage => String.t,
    :url => Uri,
    :expiresAt => DateTime.t,
    :size => integer()
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:url, :struct, Spatio.Model.Uri)
  end
end

