# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ExportPdfRequestRasterizedSlidesInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :slideId,
    :png
  ]

  @type t :: %__MODULE__{
    :slideId => String.t,
    :png => String.t
  }

  def decode(value) do
    value
  end
end

