# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ExportPdfRequest do
  @moduledoc """
  Optional body for `POST /v1/slides/{id}/export/pdf`. Renderer posts pre-rasterized PNGs for slides that contain Fabric.js elements (the sidecar can't run Fabric server-side); slides without an entry are rendered from their `layout` + theme. 
  """

  @derive JSON.Encoder
  defstruct [
    :rasterizedSlides,
    :theme
  ]

  @type t :: %__MODULE__{
    :rasterizedSlides => [Spatio.Model.ExportPdfRequestRasterizedSlidesInner.t] | nil,
    :theme => %{optional(String.t) => any()} | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:rasterizedSlides, :list, Spatio.Model.ExportPdfRequestRasterizedSlidesInner)
  end
end

