# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.FederatedSearch200ResponseItemsInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :entity_type,
    :platform,
    :provider_id,
    :title,
    :description,
    :snippet,
    :author,
    :created_at,
    :updated_at,
    :score
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :entity_type => String.t | nil,
    :platform => String.t | nil,
    :provider_id => String.t | nil,
    :title => String.t | nil,
    :description => String.t | nil,
    :snippet => String.t | nil,
    :author => String.t | nil,
    :created_at => DateTime.t | nil,
    :updated_at => DateTime.t | nil,
    :score => number() | nil
  }

  def decode(value) do
    value
  end
end

