# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.FederatedSearch200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :items,
    :next_page_tokens,
    :per_platform,
    :errors,
    :total_returned,
    :took
  ]

  @type t :: %__MODULE__{
    :items => [Spatio.Model.FederatedSearch200ResponseItemsInner.t],
    :next_page_tokens => %{optional(String.t) => String.t} | nil,
    :per_platform => %{optional(String.t) => Spatio.Model.FederatedSearch200ResponsePerPlatformValue.t},
    :errors => %{optional(String.t) => String.t} | nil,
    :total_returned => integer(),
    :took => String.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:items, :list, Spatio.Model.FederatedSearch200ResponseItemsInner)
     |> Deserializer.deserialize(:per_platform, :map, Spatio.Model.FederatedSearch200ResponsePerPlatformValue)
  end
end

