# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.FederatedSearch200ResponsePerPlatformValue do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :returned,
    :total
  ]

  @type t :: %__MODULE__{
    :returned => integer() | nil,
    :total => integer() | nil
  }

  def decode(value) do
    value
  end
end

