# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.FederatedSearchRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :query,
    :platforms,
    :limit,
    :page_tokens,
    :workspace_id,
    :organization_id,
    :include_shared,
    :include_archived
  ]

  @type t :: %__MODULE__{
    :query => String.t,
    :platforms => [String.t] | nil,
    :limit => integer() | nil,
    :page_tokens => %{optional(String.t) => String.t} | nil,
    :workspace_id => String.t | nil,
    :organization_id => String.t | nil,
    :include_shared => boolean() | nil,
    :include_archived => boolean() | nil
  }

  def decode(value) do
    value
  end
end

