# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.FileListEnvelope do
  @moduledoc """
  Fan-out list response for `GET /v1/files`.
  """

  @derive JSON.Encoder
  defstruct [
    :items,
    :accounts
  ]

  @type t :: %__MODULE__{
    :items => [Spatio.Model.SpatioFile.t] | nil,
    :accounts => [Spatio.Model.AccountStatus.t]
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:items, :list, Spatio.Model.SpatioFile)
     |> Deserializer.deserialize(:accounts, :list, Spatio.Model.AccountStatus)
  end
end

