# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.Folder do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :provider,
    :accountId,
    :name,
    :parentId,
    :path,
    :createdAt,
    :updatedAt
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :provider => String.t | nil,
    :accountId => String.t | nil,
    :name => String.t,
    :parentId => String.t | nil,
    :path => String.t,
    :createdAt => DateTime.t,
    :updatedAt => DateTime.t
  }

  def decode(value) do
    value
  end
end

