# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.GetChatUserResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :user,
    :provider
  ]

  @type t :: %__MODULE__{
    :user => Spatio.Model.ChatUser.t,
    :provider => String.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:user, :struct, Spatio.Model.ChatUser)
  end
end

