# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.GetDomainLogo200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :domain,
    :logoUrl
  ]

  @type t :: %__MODULE__{
    :domain => String.t,
    :logoUrl => String.t
  }

  def decode(value) do
    value
  end
end

