# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.InboxListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :items,
    :totalCount,
    :hasMore
  ]

  @type t :: %__MODULE__{
    :items => [Spatio.Model.InboxItem.t],
    :totalCount => integer(),
    :hasMore => boolean()
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:items, :list, Spatio.Model.InboxItem)
  end
end

