# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.InitChunkedUploadRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :fileName,
    :totalSize,
    :mimeType,
    :expectedBlocks,
    :folderId,
    :workspaceId,
    :organizationId
  ]

  @type t :: %__MODULE__{
    :fileName => String.t,
    :totalSize => integer(),
    :mimeType => String.t,
    :expectedBlocks => [String.t],
    :folderId => String.t | nil,
    :workspaceId => String.t | nil,
    :organizationId => String.t | nil
  }

  def decode(value) do
    value
  end
end

