# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.IssueCollaborationToken200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :token,
    :ws_url,
    :room,
    :expires_at,
    :expires_in
  ]

  @type t :: %__MODULE__{
    :token => String.t,
    :ws_url => String.t,
    :room => String.t | nil,
    :expires_at => DateTime.t,
    :expires_in => integer()
  }

  def decode(value) do
    value
  end
end

