# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.Jwks do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :keys
  ]

  @type t :: %__MODULE__{
    :keys => [Spatio.Model.Jwk.t]
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:keys, :list, Spatio.Model.Jwk)
  end
end

