# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.KeyBindingListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :bindings
  ]

  @type t :: %__MODULE__{
    :bindings => [Spatio.Model.KeyBinding.t]
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:bindings, :list, Spatio.Model.KeyBinding)
  end
end

