# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.KeyBinding do
  @moduledoc """
  Merged user-customized key binding.
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :actionId,
    :displayName,
    :description,
    :key,
    :modifiers,
    :category,
    :scope,
    :displayOrder,
    :isCustom,
    :metadata
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :actionId => String.t,
    :displayName => String.t | nil,
    :description => String.t | nil,
    :key => String.t | nil,
    :modifiers => [String.t] | nil,
    :category => String.t | nil,
    :scope => String.t | nil,
    :displayOrder => integer() | nil,
    :isCustom => boolean() | nil,
    :metadata => %{optional(String.t) => any()} | nil
  }

  def decode(value) do
    value
  end
end

