# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.Label do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :type,
    :messageListVisibility,
    :labelListVisibility,
    :color
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t,
    :type => String.t,
    :messageListVisibility => String.t | nil,
    :labelListVisibility => String.t | nil,
    :color => Spatio.Model.LabelColor.t | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:color, :struct, Spatio.Model.LabelColor)
  end
end

