# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ListLabelsResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :labels,
    :provider
  ]

  @type t :: %__MODULE__{
    :labels => [Spatio.Model.Label.t],
    :provider => String.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:labels, :list, Spatio.Model.Label)
  end
end

