# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ListEventsData do
  @moduledoc """
  Shape of `data` when returned by `listEvents`. Wrapped inside a CalendarOperationResult — clients should access this as `result.data` after checking `result.success`. 
  """

  @derive JSON.Encoder
  defstruct [
    :events,
    :next_page_token,
    :total_results,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :events => [Spatio.Model.SpatioEvent.t] | nil,
    :next_page_token => String.t | nil,
    :total_results => integer() | nil,
    :updated_at => DateTime.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:events, :list, Spatio.Model.SpatioEvent)
  end
end

