# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ListCalendarEvents200Response do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :success,
    :data,
    :errors,
    :metadata
  ]

  @type t :: %__MODULE__{
    :success => boolean(),
    :data => Spatio.Model.ListEventsData.t | nil,
    :errors => [Spatio.Model.CalendarAccountError.t] | nil,
    :metadata => %{optional(String.t) => any()} | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:data, :struct, Spatio.Model.ListEventsData)
     |> Deserializer.deserialize(:errors, :list, Spatio.Model.CalendarAccountError)
  end
end

