# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ListChannelsResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :channels,
    :total,
    :nextCursor,
    :provider
  ]

  @type t :: %__MODULE__{
    :channels => [Spatio.Model.Channel.t] | nil,
    :total => integer(),
    :nextCursor => String.t | nil,
    :provider => String.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:channels, :list, Spatio.Model.Channel)
  end
end

