# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ListChatUsersResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :users,
    :total,
    :nextCursor,
    :provider
  ]

  @type t :: %__MODULE__{
    :users => [Spatio.Model.ChatUser.t] | nil,
    :total => integer(),
    :nextCursor => String.t | nil,
    :provider => String.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:users, :list, Spatio.Model.ChatUser)
  end
end

