# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.MoveEmailsRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :messageIds
  ]

  @type t :: %__MODULE__{
    :messageIds => [String.t]
  }

  def decode(value) do
    value
  end
end

