# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.OrganizationMember do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :userId,
    :role,
    :joinedAt,
    :invitedBy,
    :user
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :userId => String.t,
    :role => String.t,
    :joinedAt => DateTime.t,
    :invitedBy => Spatio.Model.OrganizationMemberInvitedBy.t | nil,
    :user => %{optional(String.t) => any()} | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:invitedBy, :struct, Spatio.Model.OrganizationMemberInvitedBy)
  end
end

