# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.OrganizationMemberInvitedBy do
  @moduledoc """
  Inviter info. Returns either a bare user id (`string`) on legacy paths, or an object envelope `{id, email, name, ...}` on enriched responses. Treat as opaque. 
  """

  @derive JSON.Encoder
  defstruct [
    
  ]

  @type t :: %__MODULE__{
    
  }

  def decode(value) do
    value
  end
end

