# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.OrganizationInvitation do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :organizationId,
    :email,
    :role,
    :token,
    :expiresAt,
    :createdAt,
    :acceptedAt,
    :revokedAt,
    :invitedBy,
    :status
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :organizationId => String.t | nil,
    :email => String.t,
    :role => String.t,
    :token => String.t | nil,
    :expiresAt => DateTime.t | nil,
    :createdAt => DateTime.t,
    :acceptedAt => DateTime.t | nil,
    :revokedAt => DateTime.t | nil,
    :invitedBy => Spatio.Model.OrganizationMemberInvitedBy.t | nil,
    :status => String.t | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:invitedBy, :struct, Spatio.Model.OrganizationMemberInvitedBy)
  end
end

