# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.OrganizationMemberListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :members,
    :total
  ]

  @type t :: %__MODULE__{
    :members => [Spatio.Model.OrganizationMember.t],
    :total => integer()
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:members, :list, Spatio.Model.OrganizationMember)
  end
end

