# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.OrganizationDetailLegacy do
  @moduledoc """
  Single-organization GET response. **PascalCase keys** — inconsistent with the rest of the API (anonymous-struct json-marshal in handler with no field tags). Documented as-is; a future cleanup pass will move this to camelCase via a versioned migration. 
  """

  @derive JSON.Encoder
  defstruct [
    :ID,
    :Name,
    :Slug,
    :Description,
    :LogoURL,
    :Settings,
    :SubscriptionTier,
    :DeploymentType,
    :SubscriptionStatus,
    :CreatedAt,
    :UpdatedAt
  ]

  @type t :: %__MODULE__{
    :ID => String.t,
    :Name => String.t,
    :Slug => String.t,
    :Description => String.t | nil,
    :LogoURL => String.t | nil,
    :Settings => String.t | nil,
    :SubscriptionTier => String.t,
    :DeploymentType => String.t,
    :SubscriptionStatus => String.t,
    :CreatedAt => DateTime.t,
    :UpdatedAt => DateTime.t
  }

  def decode(value) do
    value
  end
end

