# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.PatListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :tokens,
    :availableScopes
  ]

  @type t :: %__MODULE__{
    :tokens => [Spatio.Model.PersonalAccessToken.t],
    :availableScopes => [String.t] | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:tokens, :list, Spatio.Model.PersonalAccessToken)
  end
end

