# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.PersonalAccessToken do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :description,
    :scopes,
    :workspaceId,
    :createdAt,
    :lastUsedAt,
    :expiresAt,
    :tokenPrefix
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t | nil,
    :description => String.t | nil,
    :scopes => [String.t] | nil,
    :workspaceId => String.t | nil,
    :createdAt => DateTime.t | nil,
    :lastUsedAt => DateTime.t | nil,
    :expiresAt => DateTime.t | nil,
    :tokenPrefix => String.t | nil
  }

  def decode(value) do
    value
  end
end

