# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.QuotaExceededError do
  @moduledoc """
  Returned by upload endpoints when the caller's storage quota is exhausted. `code: quota_exceeded` is reserved. 
  """

  @derive JSON.Encoder
  defstruct [
    :error,
    :code
  ]

  @type t :: %__MODULE__{
    :error => String.t,
    :code => String.t | nil
  }

  def decode(value) do
    value
  end
end

