# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.Recommendation do
  @moduledoc """
  Agent-authored proposal that surfaces on the home feed. Status transitions: `pending` → `accepted | dismissed | expired`. 
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :workspaceId,
    :userId,
    :kind,
    :title,
    :body,
    :status,
    :payload,
    :createdAt,
    :updatedAt,
    :expiresAt
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :workspaceId => String.t | nil,
    :userId => String.t | nil,
    :kind => String.t | nil,
    :title => String.t | nil,
    :body => String.t | nil,
    :status => String.t,
    :payload => %{optional(String.t) => any()} | nil,
    :createdAt => DateTime.t | nil,
    :updatedAt => DateTime.t | nil,
    :expiresAt => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

