# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.Reminder do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :method,
    :minutes
  ]

  @type t :: %__MODULE__{
    :method => Spatio.Model.ReminderMethod.t,
    :minutes => integer()
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:method, :struct, Spatio.Model.ReminderMethod)
  end
end

