# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.RevokeOtherSessionsResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :revoked
  ]

  @type t :: %__MODULE__{
    :revoked => integer() | nil
  }

  def decode(value) do
    value
  end
end

