# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.RoutineListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :items
  ]

  @type t :: %__MODULE__{
    :items => [Spatio.Model.Routine.t]
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:items, :list, Spatio.Model.Routine)
  end
end

