# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.Row do
  @moduledoc """
  A spreadsheet row. `cells` is a column-name → value map. Values are JSON primitives (string, number, boolean) or null; provider- specific richer types (formula, date) are encoded as strings. 
  """

  @derive JSON.Encoder
  defstruct [
    :index,
    :cells
  ]

  @type t :: %__MODULE__{
    :index => integer(),
    :cells => %{optional(String.t) => any()}
  }

  def decode(value) do
    value
  end
end

