# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.SearchFilesResponse do
  @moduledoc """
  In-memory substring search across the caller's files. Provider filtering isn't standardized across providers, so the platform lists up to ~500 files and filters locally — `total` is the pre-truncation count, not the global count. 
  """

  @derive JSON.Encoder
  defstruct [
    :files,
    :total,
    :hasMore,
    :query
  ]

  @type t :: %__MODULE__{
    :files => [Spatio.Model.SpatioFile.t] | nil,
    :total => integer(),
    :hasMore => boolean(),
    :query => String.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:files, :list, Spatio.Model.SpatioFile)
  end
end

