# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.SendEmailResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :success,
    :messageId,
    :threadId,
    :provider,
    :error
  ]

  @type t :: %__MODULE__{
    :success => boolean(),
    :messageId => String.t,
    :threadId => String.t | nil,
    :provider => String.t,
    :error => String.t | nil
  }

  def decode(value) do
    value
  end
end

