# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.SendChatMessageRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :accountId,
    :channel,
    :text,
    :threadId,
    :blocks
  ]

  @type t :: %__MODULE__{
    :accountId => String.t | nil,
    :channel => String.t,
    :text => String.t,
    :threadId => String.t | nil,
    :blocks => [%{optional(String.t) => any()}] | nil
  }

  def decode(value) do
    value
  end
end

