# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.Session do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :ipAddress,
    :userAgent,
    :deviceType,
    :browser,
    :os,
    :country,
    :city,
    :createdAt,
    :lastActiveAt,
    :isCurrent
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :ipAddress => String.t | nil,
    :userAgent => String.t | nil,
    :deviceType => String.t | nil,
    :browser => String.t | nil,
    :os => String.t | nil,
    :country => String.t | nil,
    :city => String.t | nil,
    :createdAt => DateTime.t | nil,
    :lastActiveAt => DateTime.t | nil,
    :isCurrent => boolean() | nil
  }

  def decode(value) do
    value
  end
end

