# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.SessionListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :sessions
  ]

  @type t :: %__MODULE__{
    :sessions => [Spatio.Model.Session.t]
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:sessions, :list, Spatio.Model.Session)
  end
end

