# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.SignInMethods do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :email,
    :hasPassword,
    :providers
  ]

  @type t :: %__MODULE__{
    :email => String.t,
    :hasPassword => boolean(),
    :providers => [Spatio.Model.SignInMethodsProvidersInner.t] | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:providers, :list, Spatio.Model.SignInMethodsProvidersInner)
  end
end

