# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.SignInMethodsProvidersInner do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :provider,
    :accountEmail,
    :linkedAt,
    :lastUsedAt
  ]

  @type t :: %__MODULE__{
    :provider => String.t,
    :accountEmail => String.t | nil,
    :linkedAt => DateTime.t | nil,
    :lastUsedAt => DateTime.t | nil
  }

  def decode(value) do
    value
  end
end

