# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.SlideElementList do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :elements,
    :total
  ]

  @type t :: %__MODULE__{
    :elements => [Spatio.Model.SlideElement.t],
    :total => integer()
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:elements, :list, Spatio.Model.SlideElement)
  end
end

