# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.SpatioConnection do
  @moduledoc """
  OAuth/native integration descriptor. Open shape — categories add provider-specific capability flags. Treat unknown fields as additive. 
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :name,
    :category,
    :description,
    :authType,
    :connected,
    :connectedAccounts,
    :capabilities,
    :gradientFrom,
    :gradientTo,
    :icon
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :name => String.t | nil,
    :category => String.t | nil,
    :description => String.t | nil,
    :authType => String.t | nil,
    :connected => boolean() | nil,
    :connectedAccounts => [%{optional(String.t) => any()}] | nil,
    :capabilities => %{optional(String.t) => any()} | nil,
    :gradientFrom => String.t | nil,
    :gradientTo => String.t | nil,
    :icon => String.t | nil
  }

  def decode(value) do
    value
  end
end

