# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.SuccessFlag do
  @moduledoc """
  Lightweight ack returned by mutations that have no other body (`DELETE /v1/notes/:id`, block move, etc.). 
  """

  @derive JSON.Encoder
  defstruct [
    :success
  ]

  @type t :: %__MODULE__{
    :success => boolean()
  }

  def decode(value) do
    value
  end
end

