# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.TaskCommentList do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :comments,
    :total
  ]

  @type t :: %__MODULE__{
    :comments => [Spatio.Model.TaskComment.t],
    :total => integer()
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:comments, :list, Spatio.Model.TaskComment)
  end
end

