# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.TextAnnotations do
  @moduledoc """
  Inline formatting flags for a `RichTextObject`.
  """

  @derive JSON.Encoder
  defstruct [
    :bold,
    :italic,
    :strikethrough,
    :underline,
    :code,
    :color
  ]

  @type t :: %__MODULE__{
    :bold => boolean(),
    :italic => boolean(),
    :strikethrough => boolean(),
    :underline => boolean(),
    :code => boolean(),
    :color => String.t | nil
  }

  def decode(value) do
    value
  end
end

