# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.TokenResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :access_token,
    :token_type,
    :expires_in,
    :refresh_token,
    :scope,
    :id_token
  ]

  @type t :: %__MODULE__{
    :access_token => String.t,
    :token_type => String.t,
    :expires_in => integer(),
    :refresh_token => String.t | nil,
    :scope => String.t | nil,
    :id_token => String.t | nil
  }

  def decode(value) do
    value
  end
end

