# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.UpdateContactCategoryRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :color,
    :description
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :color => String.t | nil,
    :description => String.t | nil
  }

  def decode(value) do
    value
  end
end

