# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.UpdateEmailFolderRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil
  }

  def decode(value) do
    value
  end
end

