# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.UpdateMessageMetadataRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :id,
    :metadata
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :metadata => %{optional(String.t) => any()} | nil
  }

  def decode(value) do
    value
  end
end

