# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.UpdateOrganizationRequest do
  @moduledoc """
  Partial update.
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :description,
    :logoUrl
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :description => String.t | nil,
    :logoUrl => Uri | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:logoUrl, :struct, Spatio.Model.Uri)
  end
end

