# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.UpdateTaskRequest do
  @moduledoc """
  Partial update — every field is optional. `dueDate` and `parentTaskId` are nullable: send `null` to clear, omit to leave untouched, send a value to set. 
  """

  @derive JSON.Encoder
  defstruct [
    :title,
    :description,
    :status,
    :dueDate,
    :priority,
    :labels,
    :tags,
    :assigneeId,
    :parentTaskId
  ]

  @type t :: %__MODULE__{
    :title => String.t | nil,
    :description => String.t | nil,
    :status => String.t | nil,
    :dueDate => DateTime.t | nil,
    :priority => String.t | nil,
    :labels => [String.t] | nil,
    :tags => [String.t] | nil,
    :assigneeId => String.t | nil,
    :parentTaskId => String.t | nil
  }

  def decode(value) do
    value
  end
end

