# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.UpdateAgentRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :description,
    :systemPrompt,
    :tools,
    :icon,
    :color,
    :metadata
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :description => String.t | nil,
    :systemPrompt => String.t | nil,
    :tools => [String.t] | nil,
    :icon => String.t | nil,
    :color => String.t | nil,
    :metadata => %{optional(String.t) => any()} | nil
  }

  def decode(value) do
    value
  end
end

