# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.UpdateSheetRequest do
  @moduledoc """
  Partial update — every field is optional.
  """

  @derive JSON.Encoder
  defstruct [
    :name,
    :description,
    :data,
    :rowCount,
    :columnCount,
    :isPublic,
    :isReadOnly
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :description => String.t | nil,
    :data => %{optional(String.t) => any()} | nil,
    :rowCount => integer() | nil,
    :columnCount => integer() | nil,
    :isPublic => boolean() | nil,
    :isReadOnly => boolean() | nil
  }

  def decode(value) do
    value
  end
end

