# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.UpdateEventRequest do
  @moduledoc """
  Sparse update. `updates` is a free-form map of fields to change; only keys present are applied. The server-side capability gate rejects fields that the underlying provider doesn't support. 
  """

  @derive JSON.Encoder
  defstruct [
    :account_id,
    :updates,
    :send_updates
  ]

  @type t :: %__MODULE__{
    :account_id => String.t,
    :updates => %{optional(String.t) => any()},
    :send_updates => String.t | nil
  }

  def decode(value) do
    value
  end
end

