# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.UpdateSlideRequest do
  @moduledoc """
  Partial update — every field optional.
  """

  @derive JSON.Encoder
  defstruct [
    :title,
    :notes,
    :layout,
    :backgroundColor,
    :backgroundImageUrl,
    :textColor,
    :transition,
    :position
  ]

  @type t :: %__MODULE__{
    :title => String.t | nil,
    :notes => String.t | nil,
    :layout => String.t | nil,
    :backgroundColor => String.t | nil,
    :backgroundImageUrl => Uri | nil,
    :textColor => String.t | nil,
    :transition => String.t | nil,
    :position => integer() | nil
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:backgroundImageUrl, :struct, Spatio.Model.Uri)
  end
end

