# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.UploadFileBase64Request do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :accountId,
    :name,
    :content,
    :mimeType,
    :folderId,
    :workspaceId,
    :organizationId,
    :metadata
  ]

  @type t :: %__MODULE__{
    :accountId => String.t | nil,
    :name => String.t,
    :content => binary(),
    :mimeType => String.t,
    :folderId => String.t | nil,
    :workspaceId => String.t | nil,
    :organizationId => String.t | nil,
    :metadata => %{optional(String.t) => any()} | nil
  }

  def decode(value) do
    value
  end
end

