# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.UserInfoResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :sub,
    :email,
    :email_verified,
    :name,
    :given_name,
    :family_name,
    :preferred_username,
    :picture,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :sub => String.t,
    :email => String.t | nil,
    :email_verified => boolean() | nil,
    :name => String.t | nil,
    :given_name => String.t | nil,
    :family_name => String.t | nil,
    :preferred_username => String.t | nil,
    :picture => String.t | nil,
    :updated_at => integer() | nil
  }

  def decode(value) do
    value
  end
end

