# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.ValidateKeyBindingResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :valid,
    :conflicts
  ]

  @type t :: %__MODULE__{
    :valid => boolean(),
    :conflicts => [%{optional(String.t) => any()}] | nil
  }

  def decode(value) do
    value
  end
end

