# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.WorkspaceInvitationListResponse do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :invitations
  ]

  @type t :: %__MODULE__{
    :invitations => [Spatio.Model.WorkspaceInvitation.t]
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:invitations, :list, Spatio.Model.WorkspaceInvitation)
  end
end

