# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.WorkspaceEnvelope do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :workspace
  ]

  @type t :: %__MODULE__{
    :workspace => Spatio.Model.Workspace.t
  }

  alias Spatio.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:workspace, :struct, Spatio.Model.Workspace)
  end
end

