# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Model.WriteAppFileRequest do
  @moduledoc """
  
  """

  @derive JSON.Encoder
  defstruct [
    :path,
    :content
  ]

  @type t :: %__MODULE__{
    :path => String.t,
    :content => String.t
  }

  def decode(value) do
    value
  end
end

