# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Api.Channels do
  @moduledoc """
  API calls for all endpoints tagged `Channels`.
  """

  alias Spatio.Connection
  import Spatio.RequestBuilder

  @doc """
  Create a channel.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `create_channel_request` (CreateChannelRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.CreateChannelResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_channel(Tesla.Env.client, Spatio.Model.CreateChannelRequest.t, keyword()) :: {:ok, Spatio.Model.CreateChannelResponse.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def create_channel(connection, create_channel_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/channels")
      |> add_param(:body, :body, create_channel_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Spatio.Model.CreateChannelResponse},
      {400, Spatio.Model.ApiError},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Dispatch a channel action by id.
  Generic action-execution endpoint. `params` shape varies per `action_id`; consult `GET /v1/channels/actions` for the per-id contract. 

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `execute_chat_action_request` (ExecuteChatActionRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.ExecuteChatActionResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec execute_channel_action(Tesla.Env.client, Spatio.Model.ExecuteChatActionRequest.t, keyword()) :: {:ok, Spatio.Model.ExecuteChatActionResponse.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def execute_channel_action(connection, execute_chat_action_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/channels/execute")
      |> add_param(:body, :body, execute_chat_action_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.ExecuteChatActionResponse},
      {400, Spatio.Model.ApiError},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Join a channel.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `id` (String.t): Channel id (provider-scoped).
  - `opts` (keyword): Optional parameters
    - `:body` (ChannelMembershipRequest): 

  ### Returns

  - `{:ok, Spatio.Model.SuccessFlag.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec join_channel(Tesla.Env.client, String.t, keyword()) :: {:ok, Spatio.Model.ApiError.t} | {:ok, Spatio.Model.SuccessFlag.t} | {:error, Tesla.Env.t}
  def join_channel(connection, id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/v1/channels/#{id}/join")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.SuccessFlag},
      {400, Spatio.Model.ApiError},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Leave a channel.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `id` (String.t): Channel id (provider-scoped).
  - `opts` (keyword): Optional parameters
    - `:body` (ChannelMembershipRequest): 

  ### Returns

  - `{:ok, Spatio.Model.SuccessFlag.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec leave_channel(Tesla.Env.client, String.t, keyword()) :: {:ok, Spatio.Model.ApiError.t} | {:ok, Spatio.Model.SuccessFlag.t} | {:error, Tesla.Env.t}
  def leave_channel(connection, id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/v1/channels/#{id}/leave")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.SuccessFlag},
      {400, Spatio.Model.ApiError},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Discover the action catalog for the Channels platform.
  Returns the action descriptors the agent layer dispatches via `POST /v1/channels/execute`. Same pattern as the DirectMessages action surface. 

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.ChatActionsList.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_channel_actions(Tesla.Env.client, keyword()) :: {:ok, Spatio.Model.ChatActionsList.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def list_channel_actions(connection, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/channels/actions")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.ChatActionsList},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  List messages in a channel.
  Channel ids are provider-scoped; pass `?accountId=` (preferred) or `?accountIds=` to disambiguate when the same id exists on multiple connected accounts (rare). 

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `channel` (String.t): Channel id.
  - `opts` (keyword): Optional parameters
    - `:accountId` (String.t): 
    - `:accountIds` ([String.t]): Repeatable. Restrict to these connected-account row ids. Mutually orthogonal to `providers` — when both are set the intersection is used. 
    - `:providers` ([String.t]): Repeatable. Restrict to these provider ids (`gmail`, `outlook`).
    - `:"X-Workspace-ID"` (String.t): Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
    - `:limit` (integer()): 
    - `:cursor` (String.t): 
    - `:oldestFirst` (boolean()): 

  ### Returns

  - `{:ok, Spatio.Model.ListMessagesResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_channel_messages(Tesla.Env.client, String.t, keyword()) :: {:ok, Spatio.Model.ListMessagesResponse.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def list_channel_messages(connection, channel, opts \\ []) do
    optional_params = %{
      :accountId => :query,
      :accountIds => :query,
      :providers => :query,
      :"X-Workspace-ID" => :headers,
      :limit => :query,
      :cursor => :query,
      :oldestFirst => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/channels/messages")
      |> add_param(:query, :channel, channel)
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.ListMessagesResponse},
      {400, Spatio.Model.ApiError},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  List group channels across connected chat providers.
  Fan-out list. The Channels surface filters to channel-type conversations only (`type: channel | private`); for direct messages use `/v1/direct-messages`. 

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:accountIds` ([String.t]): Repeatable. Restrict to these connected-account row ids. Mutually orthogonal to `providers` — when both are set the intersection is used. 
    - `:providers` ([String.t]): Repeatable. Restrict to these provider ids (`gmail`, `outlook`).
    - `:"X-Workspace-ID"` (String.t): Workspace scope for unscoped tokens. Workspace-scoped PATs and OAuth tokens carry this implicitly; for session/JWT auth without a scoped PAT, pass it explicitly. 
    - `:limit` (integer()): 
    - `:cursor` (String.t): Provider-specific pagination cursor.
    - `:includeArchived` (boolean()): 
    - `:types` ([String.t]): Repeatable filter on `Channel.type`. Defaults applied by the platform exclude DMs; passing this overrides. 

  ### Returns

  - `{:ok, Spatio.Model.ListChannelsResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_channels(Tesla.Env.client, keyword()) :: {:ok, Spatio.Model.ListChannelsResponse.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def list_channels(connection, opts \\ []) do
    optional_params = %{
      :accountIds => :query,
      :providers => :query,
      :"X-Workspace-ID" => :headers,
      :limit => :query,
      :cursor => :query,
      :includeArchived => :query,
      :types => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/channels")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.ListChannelsResponse},
      {401, Spatio.Model.ApiError},
      {500, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Send a message to a channel.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `send_chat_message_request` (SendChatMessageRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.SendChatMessageResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec send_channel_message(Tesla.Env.client, Spatio.Model.SendChatMessageRequest.t, keyword()) :: {:ok, Spatio.Model.SendChatMessageResponse.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def send_channel_message(connection, send_chat_message_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/channels/messages")
      |> add_param(:body, :body, send_chat_message_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.SendChatMessageResponse},
      {400, Spatio.Model.ApiError},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `org` (String.t): 
  - `workspace` (String.t): 
  - `request_body` (%{optional(String.t) => any()}): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec workspace_create_channel(Tesla.Env.client, String.t, String.t, %{optional(String.t) => any()}, keyword()) :: {:ok, %{optional(String.t) => any()}} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def workspace_create_channel(connection, org, workspace, request_body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/organizations/#{org}/workspaces/#{workspace}/channels")
      |> add_param(:body, :body, request_body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, %{}},
      {401, Spatio.Model.ApiError},
      {403, Spatio.Model.ApiError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `org` (String.t): 
  - `workspace` (String.t): 
  - `request_body` (%{optional(String.t) => any()}): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec workspace_execute_channel_action(Tesla.Env.client, String.t, String.t, %{optional(String.t) => any()}, keyword()) :: {:ok, %{optional(String.t) => any()}} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def workspace_execute_channel_action(connection, org, workspace, request_body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/organizations/#{org}/workspaces/#{workspace}/channels/execute")
      |> add_param(:body, :body, request_body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {401, Spatio.Model.ApiError},
      {403, Spatio.Model.ApiError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `org` (String.t): 
  - `workspace` (String.t): 
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:body` (%{optional(String.t) &#x3D;&gt; any()}): 

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec workspace_join_channel(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def workspace_join_channel(connection, org, workspace, id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/v1/organizations/#{org}/workspaces/#{workspace}/channels/#{id}/join")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {401, Spatio.Model.ApiError},
      {403, Spatio.Model.ApiError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `org` (String.t): 
  - `workspace` (String.t): 
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:body` (%{optional(String.t) &#x3D;&gt; any()}): 

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec workspace_leave_channel(Tesla.Env.client, String.t, String.t, String.t, keyword()) :: {:ok, nil} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def workspace_leave_channel(connection, org, workspace, id, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/v1/organizations/#{org}/workspaces/#{workspace}/channels/#{id}/leave")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {401, Spatio.Model.ApiError},
      {403, Spatio.Model.ApiError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `org` (String.t): 
  - `workspace` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec workspace_list_channel_actions(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, %{optional(String.t) => any()}} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def workspace_list_channel_actions(connection, org, workspace, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/organizations/#{org}/workspaces/#{workspace}/channels/actions")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {401, Spatio.Model.ApiError},
      {403, Spatio.Model.ApiError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `org` (String.t): 
  - `workspace` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec workspace_list_channel_messages(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, %{optional(String.t) => any()}} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def workspace_list_channel_messages(connection, org, workspace, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/organizations/#{org}/workspaces/#{workspace}/channels/messages")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {401, Spatio.Model.ApiError},
      {403, Spatio.Model.ApiError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `org` (String.t): 
  - `workspace` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec workspace_list_channels(Tesla.Env.client, String.t, String.t, keyword()) :: {:ok, %{optional(String.t) => any()}} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def workspace_list_channels(connection, org, workspace, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/organizations/#{org}/workspaces/#{workspace}/channels")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {401, Spatio.Model.ApiError},
      {403, Spatio.Model.ApiError}
    ])
  end

  @doc """

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `org` (String.t): 
  - `workspace` (String.t): 
  - `request_body` (%{optional(String.t) => any()}): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, %{}}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec workspace_send_channel_message(Tesla.Env.client, String.t, String.t, %{optional(String.t) => any()}, keyword()) :: {:ok, %{optional(String.t) => any()}} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def workspace_send_channel_message(connection, org, workspace, request_body, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/organizations/#{org}/workspaces/#{workspace}/channels/messages")
      |> add_param(:body, :body, request_body)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, %{}},
      {401, Spatio.Model.ApiError},
      {403, Spatio.Model.ApiError}
    ])
  end
end
