# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Api.Conversations do
  @moduledoc """
  API calls for all endpoints tagged `Conversations`.
  """

  alias Spatio.Connection
  import Spatio.RequestBuilder

  @doc """
  Persist a new LLM conversation.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:body` (CreateConversationRequest): 

  ### Returns

  - `{:ok, Spatio.Model.Conversation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec create_conversation(Tesla.Env.client, keyword()) :: {:ok, Spatio.Model.Conversation.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def create_conversation(connection, opts \\ []) do
    optional_params = %{
      :body => :body
    }

    request =
      %{}
      |> method(:post)
      |> url("/v1/conversations")
      |> add_optional_params(optional_params, opts)
      |> ensure_body()
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Spatio.Model.Conversation},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Soft-delete a conversation.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_conversation(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def delete_conversation(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/v1/conversations/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Fetch one conversation.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.Conversation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_conversation(Tesla.Env.client, String.t, keyword()) :: {:ok, Spatio.Model.Conversation.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def get_conversation(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/conversations/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.Conversation},
      {401, Spatio.Model.ApiError},
      {404, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Fetch the most recently active conversation for a given context tag.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `context` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.Conversation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_latest_conversation_for_context(Tesla.Env.client, String.t, keyword()) :: {:ok, Spatio.Model.Conversation.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def get_latest_conversation_for_context(connection, context, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/conversations/latest")
      |> add_param(:query, :context, context)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.Conversation},
      {401, Spatio.Model.ApiError},
      {404, Spatio.Model.ApiError}
    ])
  end

  @doc """
  List messages in a conversation.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters
    - `:limit` (integer()): 
    - `:before` (String.t): 

  ### Returns

  - `{:ok, [%ConversationMessage{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_conversation_messages(Tesla.Env.client, String.t, keyword()) :: {:ok, [Spatio.Model.ConversationMessage.t]} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def list_conversation_messages(connection, id, opts \\ []) do
    optional_params = %{
      :limit => :query,
      :before => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/conversations/#{id}/messages")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.ConversationMessage},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  List the caller's persisted LLM conversations.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:context` (String.t): 
    - `:limit` (integer()): 

  ### Returns

  - `{:ok, [%Conversation{}, ...]}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_conversations(Tesla.Env.client, keyword()) :: {:ok, [Spatio.Model.Conversation.t]} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def list_conversations(connection, opts \\ []) do
    optional_params = %{
      :context => :query,
      :limit => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/conversations")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.Conversation},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Append a message to a conversation.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `id` (String.t): 
  - `save_message_request` (SaveMessageRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.ConversationMessage.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec save_conversation_message(Tesla.Env.client, String.t, Spatio.Model.SaveMessageRequest.t, keyword()) :: {:ok, Spatio.Model.ConversationMessage.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def save_conversation_message(connection, id, save_message_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/conversations/#{id}/messages")
      |> add_param(:body, :body, save_message_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Spatio.Model.ConversationMessage},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Update conversation metadata (title, context, cwd, session_id, pinned).

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `id` (String.t): 
  - `update_conversation_request` (UpdateConversationRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.Conversation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_conversation(Tesla.Env.client, String.t, Spatio.Model.UpdateConversationRequest.t, keyword()) :: {:ok, Spatio.Model.Conversation.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def update_conversation(connection, id, update_conversation_request, _opts \\ []) do
    request =
      %{}
      |> method(:patch)
      |> url("/v1/conversations/#{id}")
      |> add_param(:body, :body, update_conversation_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.Conversation},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Patch metadata on an existing message. Body must include the message id (path is the conversation id, not the message). 

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `id` (String.t): 
  - `update_message_metadata_request` (UpdateMessageMetadataRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.ConversationMessage.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_conversation_message_metadata(Tesla.Env.client, String.t, Spatio.Model.UpdateMessageMetadataRequest.t, keyword()) :: {:ok, Spatio.Model.ConversationMessage.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def update_conversation_message_metadata(connection, id, update_message_metadata_request, _opts \\ []) do
    request =
      %{}
      |> method(:patch)
      |> url("/v1/conversations/#{id}/messages")
      |> add_param(:body, :body, update_message_metadata_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.ConversationMessage},
      {401, Spatio.Model.ApiError}
    ])
  end
end
