# NOTE: This file is auto generated by OpenAPI Generator 7.22.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Spatio.Api.Recommendations do
  @moduledoc """
  API calls for all endpoints tagged `Recommendations`.
  """

  alias Spatio.Connection
  import Spatio.RequestBuilder

  @doc """
  Delete a recommendation (hard delete; status-update is preferred).

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, nil}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec delete_recommendation(Tesla.Env.client, String.t, keyword()) :: {:ok, nil} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def delete_recommendation(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:delete)
      |> url("/v1/recommendations/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {204, false},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Fetch one recommendation.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `id` (String.t): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.Recommendation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec get_recommendation(Tesla.Env.client, String.t, keyword()) :: {:ok, Spatio.Model.ApiError.t} | {:ok, Spatio.Model.Recommendation.t} | {:error, Tesla.Env.t}
  def get_recommendation(connection, id, _opts \\ []) do
    request =
      %{}
      |> method(:get)
      |> url("/v1/recommendations/#{id}")
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.Recommendation},
      {401, Spatio.Model.ApiError},
      {404, Spatio.Model.ApiError}
    ])
  end

  @doc """
  List recommendations for a workspace.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `opts` (keyword): Optional parameters
    - `:workspaceId` (String.t): 
    - `:status` (String.t): 
    - `:limit` (integer()): 

  ### Returns

  - `{:ok, Spatio.Model.RecommendationListResponse.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec list_recommendations(Tesla.Env.client, keyword()) :: {:ok, Spatio.Model.RecommendationListResponse.t} | {:ok, Spatio.Model.ApiError.t} | {:error, Tesla.Env.t}
  def list_recommendations(connection, opts \\ []) do
    optional_params = %{
      :workspaceId => :query,
      :status => :query,
      :limit => :query
    }

    request =
      %{}
      |> method(:get)
      |> url("/v1/recommendations")
      |> add_optional_params(optional_params, opts)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.RecommendationListResponse},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Agent-side propose endpoint (the `spatio_recommendations propose` MCP tool calls this).

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `propose_recommendation_request` (ProposeRecommendationRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.Recommendation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec propose_recommendation(Tesla.Env.client, Spatio.Model.ProposeRecommendationRequest.t, keyword()) :: {:ok, Spatio.Model.ApiError.t} | {:ok, Spatio.Model.Recommendation.t} | {:error, Tesla.Env.t}
  def propose_recommendation(connection, propose_recommendation_request, _opts \\ []) do
    request =
      %{}
      |> method(:post)
      |> url("/v1/recommendations")
      |> add_param(:body, :body, propose_recommendation_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {201, Spatio.Model.Recommendation},
      {401, Spatio.Model.ApiError}
    ])
  end

  @doc """
  Accept or dismiss a recommendation.

  ### Parameters

  - `connection` (Spatio.Connection): Connection to server
  - `id` (String.t): 
  - `update_recommendation_status_request` (UpdateRecommendationStatusRequest): 
  - `opts` (keyword): Optional parameters

  ### Returns

  - `{:ok, Spatio.Model.Recommendation.t}` on success
  - `{:error, Tesla.Env.t}` on failure
  """
  @spec update_recommendation_status(Tesla.Env.client, String.t, Spatio.Model.UpdateRecommendationStatusRequest.t, keyword()) :: {:ok, Spatio.Model.ApiError.t} | {:ok, Spatio.Model.Recommendation.t} | {:error, Tesla.Env.t}
  def update_recommendation_status(connection, id, update_recommendation_status_request, _opts \\ []) do
    request =
      %{}
      |> method(:patch)
      |> url("/v1/recommendations/#{id}/status")
      |> add_param(:body, :body, update_recommendation_status_request)
      |> Enum.into([])

    connection
    |> Connection.request(request)
    |> evaluate_response([
      {200, Spatio.Model.Recommendation},
      {401, Spatio.Model.ApiError},
      {404, Spatio.Model.ApiError}
    ])
  end
end
